# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
  - repo: self

variables:
  vmImageNameDefault: 'ubuntu-22.04'
  imageRepository: '$(K8S_IMAGE_REPOSITORY_NAME)'
  deployNamespace: '$(DEPLOY_NAMESPACE)'
  helmReleaseName : '$(HELM_RELEASE_NAME)'
  environment: '$(TF_ENVIRONMENT)'
  dockerRegistryServiceConnection: '$(TF_DOCKERREGISTRYSERVICECONNECTION)'
  kubernetesServiceConnection: '$(TF_KUBERNETESSERVICECONNECTION)'
  containerRegistry: '$(TF_CONTAINERREGISTRY)'
  selfHostedAgentPool: '$(TF_SELFHOSTEDAGENTPOOL)'

stages:
  - stage: 'Build'
    displayName: 'Build_and_Publish'
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageNameDefault)
        steps:
          - task: Docker@2
            displayName: 'Publish_image'
            condition: succeeded()
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: '$(imageRepository)'
              command: 'buildAndPush'
              tags: |
                $(Build.BuildId)
                latest

  - stage: 'publish_artifact_helm'
    displayName: 'Publish_artifact_Helm'
    dependsOn: ['build']
    jobs:
      - job: Publish_artifact_helm_1mb
        displayName: Publish_artifact_helm_1mb
        pool:
          vmImage: $(vmImageNameDefault)
        steps:
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Artifact manifests'
            condition: succeeded()
            inputs:
              targetPath: '$(Build.Repository.LocalPath)/1mb'
              artifact: '1mb'
              publishLocation: 'pipeline'

  - stage: 'deploy'
    displayName: 'Deploy to K8S'
    dependsOn: ['publish_artifact_helm']
    jobs:
      - deployment: 'Deploy_1mb'
        displayName: 'Deploy to K8S 1mb'
        pool:
          name: $(selfHostedAgentPool)
        environment: '$(environment)'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: 'current'
                    artifactName: '1mb'
                    targetPath: '$(Pipeline.Workspace)/1mb'
                - task: Bash@3
                  name: helm_dependency_build
                  displayName: Helm dependency build
                  inputs:
                    workingDirectory: '$(Pipeline.Workspace)/1mb'
                    targetType: 'inline'
                    script: |
                      helm repo add pagopa-microservice https://pagopa.github.io/aks-microservice-chart-blueprint
                      helm dep build
                    failOnStderr: true
                - task: HelmDeploy@0
                  displayName: Helm upgrade
                  inputs:
                    kubernetesServiceEndpoint: ${{ variables.kubernetesServiceConnection }}
                    namespace: '$(deployNamespace)'
                    command: upgrade
                    chartType: filepath
                    chartPath: $(Pipeline.Workspace)/1mb
                    chartName: ${{ variables.helmReleaseName }}
                    releaseName: ${{ variables.helmReleaseName }}
                    valueFile: '$(Pipeline.Workspace)/1mb/values-${{ variables.environment }}.yaml'
                    install: true
                    waitForExecution: true
                    arguments: "--timeout 3m0s --debug"
