microservice-chart:
  namespace: tae

  image:
    repository: cstardcommonacr.azurecr.io/infrasftptest
    tag: "latest"

  ingress:
    create: false

  service:
    create: false

  resources:
    requests:
      memory: 20Mi
      cpu: 100m
    limits:
      memory: 1540Mi
      cpu: 1000m

  envConfig:
    FUNCTION_WORKER_RUNTIME: dotnet
    TIME_TRIGGER: "0 0 * * * *"
    FunctionName: sftp4gb-test
    FileSizeInMb: "4096"
    Region: West Europe
    SftpHost: cstardsftp.blob.core.windows.net

  envSecret:
    WEBSITE_SITE_NAME: 'sftp-test-4gb' # required to show cloud role name in application insights
    APPINSIGHTS_INSTRUMENTATIONKEY: infra-sftp-test-appinsights-instrumentationkey
    AzureWebJobsStorage: infra-sftp-test-azurewebjobsstorage
    SftpUsername: infra-sftp-test-username
    SftpPassword: infra-sftp-test-password

  keyvault:
    name: cstar-d-tae-kv
    tenantId: 7788edaf-0346-4068-9d79-c868aed15b3d
